version: "3"
# services:
#     qpsqldbbase:
#         image: microsoft/mssql-server-linux:latest
#         ports:
#             - "2048:1433"
#         container_name: qpsqldbbase
#         environment:
#             - ACCEPT_EULA=Y
#             - SA_PASSWORD=QpAdmin1
#             - MSSQL_PID=Enterprise
#         volumes:
#             - ./Data/:/var/opt/qpdata

# networks:
#     app-tier:
#         driver: bridge

# services:

# mongodb:
#     image: mongo
#     restart: always
#     environment:
#         MONGO_INITDB_ROOT_USERNAME: root
#         MONGO_INITDB_ROOT_PASSWORD: 123456
#     ports:
#         - "27017:27017"

# networks:
#   byfn:

# services:
#   etcd1:
#     image: ascs/etcd:3.3.10
#     restart: always
#     container_name: etcd1
#     command: etcd -name etcd1 -advertise-client-urls http://192.168.6.132:32775 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:32774 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:32774,etcd2=http://etcd2:32776,etcd3=http://etcd3:32778" -initial-cluster-state new
#     ports:
#     - "32775:2379"
# #         - "32774:2380"
# #     networks:
# #       - byfn

services:
    # etcd:
    #     container_name: etcd0
    #     image: registry.cn-hangzhou.aliyuncs.com/coreos_etcd/etcd:v3
    #     ports:
    #         - "2379:2379"
    #         - "4001:4001"
    #         - "2380:2380"
    #     environment:
    #         - TZ=CST-8
    #         - LANG=zh_CN.UTF-8
    #     command: /usr/local/bin/etcd
    #         -name etcd0
    #         -data-dir /etcd-data
    #         -advertise-client-urls http://${host_ip}:2379,http://${host_ip}:4001
    #         -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
    #         -initial-advertise-peer-urls http://${host_ip}:2380
    #         -listen-peer-urls http://0.0.0.0:2380
    #         -initial-cluster-token docker-etcd
    #         -initial-cluster etcd0=http://${host_ip}:2380
    #         -initial-cluster-state new
    #     volumes:
    #         - "/data/conf/etcd/data:/etcd-data"
    #         # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
    #     labels:
    #         - project.source=
    #         - project.extra=public-image
    #         - project.depends=
    #         - project.owner=LHZ

    # etcd1:
    #     image: bitnami/etcd:3
    #     environment:
    #         - ALLOW_NONE_AUTHENTICATION=yes
    #         - ETCD_NAME=etcd1
    #         - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
    #         - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    #         - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    #         - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
    #         - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    #         # - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
    #         - ETCD_INITIAL_CLUSTER_STATE=new
    #     ports:
    #         - "2379:2379"
    #         # - "4001:4001"
    #         - "2380:2380"

    # etcd 配置文章
    # https://blog.csdn.net/huwh_/article/details/80225902
    # https://www.jianshu.com/p/44022c67f117
    etcd:
        image: "bitnami/etcd:latest"
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
        ports:
            - 2379:2379
            - 2380:2380
# myapp:
#     image: "YOUR_APPLICATION_IMAGE"
#     networks:
#         - app-tier
